project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Proseminar in Geocomputation and Earth Observation"
  subtitle: "Answering geography and environmental science questions with data"
  author: "Pepa Arán and Benjamin Stocker"
  date: "2023/08/30"
  page-navigation: true
  chapters:
    - index.qmd
    - logistics.qmd
    - resources.qmd
    - public_data.qmd
    - project_ideas.qmd
    - citations.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/R_book_template/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
