# Essential contents {#sec-agds}

The following contents from [AGDS book](https://geco-bern.github.io/agds_book) are an essential basis for the Proseminar:

- [Primers](https://geco-bern.github.io/agds_book/primers.html): Introduces basics of the R programming language and provides instructions for setting up the working environment with RStudio, including the installation of libraries used in this book.
- [Reusable workflows](https://geco-bern.github.io/agds_book/reproducible_workflows.html): Motivates the adoption of reusable, project-oriented workflows and provides a guide for implementing them.
- [Code Management](https://geco-bern.github.io/agds_book/code_management.html): Introduces the essentials of code version control using Git.
- [Data variety](https://geco-bern.github.io/agds_book/data_variety.html): Introduces a classification of different data types and how to work with them.
- [Data wrangling](https://geco-bern.github.io/agds_book/data_wrangling.html): Introduces how to efficiently interpret and transform tabular data.
- [Data visualisation](https://geco-bern.github.io/agds_book/data_vis.html): Introduces the concept and logic for how to visualise different data types and axes of variation in the data.

The remaining chapters of the [AGDS book](https://geco-bern.github.io/agds_book) focus more on modelling. We encourage you to go back to those for consultation, whenever you need them for your implementation.

Additionally, you may want to get additional information on how to work with geospatial data, and with NetCDF files in particular.

- [Geospatial data in R](https://geco-bern.github.io/handfull_of_pixels/geospatial_R.html): This teaches important skills that were not covered in AGDS I, but will be used in most Proseminar projects. It includes very useful information on reading several types of geospatial data (raster and shape files), performing operations and plotting, with examples with the most used R packages.
- [NetCDF in R](https://pjbartlein.github.io/REarthSysSci/netCDF.html): Chapter in *R for Earth-System Science* by Pat Bartlein.
- [CDO](https://code.mpimet.mpg.de/projects/cdo/wiki/tutorial): A tutorial for the Climate Data Operators (CDO) -- a collection of functions that enable extremely efficient data file manipuations from the terminal (shell).
